runtime: php72

env_variables:
  ## Put production environment variables here.
  LOG_CHANNEL: stackdriver
  APP_KEY: base64:XZruUZthLdnxNjbMsqsJvaMiE+pnzYieQeTbfZTzbm8=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: vacation
  DB_USERNAME: root
  DB_PASSWORD: root
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/vacation-321816:asia-east1:vacation"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"
